const WORKS_DATA = [
  {
    "id": 1,
    "title": "PIANIST",
    "size": "60 X 70 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P001",
    "price": 18000,
    "status": "sale",
    "series": "music",
    "img": "images/art_01.jpg"
  },
  {
    "id": 2,
    "title": "GUITARIST",
    "size": "66 X 76 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P002",
    "price": 19000,
    "status": "sale",
    "series": "music",
    "img": "images/art_02.jpg"
  },
  {
    "id": 3,
    "title": "DANCING",
    "size": "110 X 120 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P003",
    "price": 24000,
    "status": "sale",
    "series": "music",
    "img": "images/art_03.jpg"
  },
  {
    "id": 4,
    "title": "FERRIS WHEEL",
    "size": "110 X 120 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P004",
    "price": 24000,
    "status": "sale",
    "series": "dream",
    "img": "images/art_04.jpg"
  },
  {
    "id": 5,
    "title": "MOON IN THE BOTTLE",
    "size": "110 X 120 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P005",
    "price": 24000,
    "status": "sale",
    "series": "dream",
    "img": "images/art_05.jpg"
  },
  {
    "id": 6,
    "title": "THE PINK CAR",
    "size": "95 X 103 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P006",
    "price": 20000,
    "status": "sale",
    "series": "dream",
    "img": "images/art_06.jpg"
  },
  {
    "id": 7,
    "title": "AMULETTO 1",
    "size": "60 X 60 CM",
    "technique": "Acrylic on hand-woven cotton fabric",
    "code": "TAH3P007",
    "price": 14000,
    "status": "sale",
    "series": "amuletto",
    "img": "images/art_07.jpg"
  },
  {
    "id": 8,
    "title": "AMULETTO 2",
    "size": "60 X 70 CM",
    "technique": "Acrylic on hand-woven cotton fabric",
    "code": "TAH3P008",
    "price": 14000,
    "status": "sale",
    "series": "amuletto",
    "img": "images/art_08.jpg"
  },
  {
    "id": 9,
    "title": "AMULETTO 3",
    "size": "60 X 70 CM",
    "technique": "Acrylic on hand-woven cotton fabric",
    "code": "TAH3P009",
    "price": 14000,
    "status": "sale",
    "series": "amuletto",
    "img": "images/art_09.jpg"
  },
  {
    "id": 10,
    "title": "AMULETTO 4",
    "size": "60 X 70 CM",
    "technique": "Acrylic on hand-woven cotton fabric",
    "code": "TAH3P010",
    "price": 14000,
    "status": "sale",
    "series": "amuletto",
    "img": "images/art_10.jpg"
  },
  {
    "id": 11,
    "title": "AMULETTO 5",
    "size": "60 X 70 CM",
    "technique": "Acrylic on hand-woven cotton fabric",
    "code": "TAH3P011",
    "price": 14000,
    "status": "sale",
    "series": "amuletto",
    "img": "images/art_11.jpg"
  },
  {
    "id": 12,
    "title": "THE THREE DEFILEMENTS 1",
    "size": "60 X 70 CM",
    "technique": "Acrylic on hand-woven cotton fabric",
    "code": "TAH3P012",
    "price": 16000,
    "status": "sale",
    "series": "defilements",
    "img": "images/art_12.jpg"
  },
  {
    "id": 13,
    "title": "THE THREE DEFILEMENTS 2",
    "size": "60 X 70 CM",
    "technique": "Acrylic on hand-woven cotton fabric",
    "code": "TAH3P013",
    "price": 16000,
    "status": "sale",
    "series": "defilements",
    "img": "images/art_13.jpg"
  },
  {
    "id": 14,
    "title": "THE THREE DEFILEMENTS 3",
    "size": "60 X 70 CM",
    "technique": "Acrylic on hand-woven cotton fabric",
    "code": "TAH3P014",
    "price": 16000,
    "status": "sale",
    "series": "defilements",
    "img": "images/art_14.jpg"
  },
  {
    "id": 15,
    "title": "TALES FROM THE FLYING LOCOMOTIVE 1",
    "size": "90 X 85 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P015",
    "price": 17000,
    "status": "sale",
    "series": "locomotive",
    "img": "images/art_15.jpg"
  },
  {
    "id": 16,
    "title": "TALES FROM THE FLYING LOCOMOTIVE 2",
    "size": "70 X 80 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P016",
    "price": 17000,
    "status": "sale",
    "series": "locomotive",
    "img": "images/art_16.jpg"
  },
  {
    "id": 17,
    "title": "LIFE CYCLE",
    "size": "100 X 110 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P017",
    "price": 20000,
    "status": "sale",
    "series": "dream",
    "img": "images/art_17.jpg"
  },
  {
    "id": 18,
    "title": "SPACE CIRCUS 1",
    "size": "90 X 85 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P018",
    "price": 17000,
    "status": "sale",
    "series": "circus",
    "img": "images/art_18.jpg"
  },
  {
    "id": 19,
    "title": "SPACE CIRCUS 2",
    "size": "90 X 85 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P019",
    "price": 17000,
    "status": "sale",
    "series": "circus",
    "img": "images/art_19.jpg"
  },
  {
    "id": 20,
    "title": "THE FORGETTING FLOWER 1",
    "size": "90 X 85 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P020",
    "price": 17000,
    "status": "sale",
    "series": "forgetting",
    "img": "images/art_20.jpg"
  },
  {
    "id": 21,
    "title": "THE FORGETTING FLOWER 2",
    "size": "90 X 85 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P021",
    "price": 17000,
    "status": "sale",
    "series": "forgetting",
    "img": "images/art_21.jpg"
  },
  {
    "id": 22,
    "title": "SPARROW SONG",
    "size": "100 X 110 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P022",
    "price": 20000,
    "status": "sale",
    "series": "dream",
    "img": "images/art_22.jpg"
  },
  {
    "id": 23,
    "title": "HOURGLASS",
    "size": "40 X 40 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P023",
    "price": 3500,
    "status": "sale",
    "series": "small",
    "img": "images/art_23.jpg"
  },
  {
    "id": 24,
    "title": "MAGPIE ROBIN",
    "size": "40 X 40 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P024",
    "price": 3500,
    "status": "sale",
    "series": "small",
    "img": "images/art_24.jpg"
  },
  {
    "id": 25,
    "title": "GOODBYE LAIKA",
    "size": "40 X 40 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P025",
    "price": 3500,
    "status": "sale",
    "series": "small",
    "img": "images/art_25.jpg"
  },
  {
    "id": 26,
    "title": "FLOAT",
    "size": "40 X 40 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P026",
    "price": 3500,
    "status": "sale",
    "series": "small",
    "img": "images/art_26.jpg"
  },
  {
    "id": 27,
    "title": "THE WAGGING TAIL",
    "size": "78 X 87 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P027",
    "price": 9500,
    "status": "sale",
    "series": "wagging",
    "img": "images/art_27.jpg"
  },
  {
    "id": 28,
    "title": "BLACK BIRD",
    "size": "78 X 87 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P028",
    "price": 9500,
    "status": "sale",
    "series": "wagging",
    "img": "images/art_28.jpg"
  },
  {
    "id": 29,
    "title": "TWIN HEAD GIANT",
    "size": "78 X 87 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P029",
    "price": 9500,
    "status": "sale",
    "series": "wagging",
    "img": "images/art_29.jpg"
  },
  {
    "id": 30,
    "title": "BLUE MAN SWING",
    "size": "78 X 87 CM",
    "technique": "Acrylic on canvas",
    "code": "TAH3P030",
    "price": 9500,
    "status": "sale",
    "series": "wagging",
    "img": "images/art_30.jpg"
  },
  {
    "id": 31,
    "title": "THE INNER UNIVERSE",
    "size": "200 X 97 CM",
    "technique": "Acrylic on hand-woven cotton fabric",
    "code": "TAH3P031",
    "price": 28000,
    "status": "sale",
    "series": "dream",
    "img": "images/art_31.jpg"
  },
  {
    "id": 32,
    "title": "ILLUSTRATION 1",
    "size": "60 X 70 CM",
    "technique": "Acrylic on hand-woven cotton fabric",
    "code": "TAH3P032",
    "price": 0,
    "status": "display",
    "series": "illustration",
    "img": "images/art_32.jpg"
  },
  {
    "id": 33,
    "title": "ILLUSTRATION 2",
    "size": "60 X 70 CM",
    "technique": "Acrylic on hand-woven cotton fabric",
    "code": "TAH3P033",
    "price": 0,
    "status": "display",
    "series": "illustration",
    "img": "images/art_33.jpg"
  },
  {
    "id": 34,
    "title": "ILLUSTRATION 3",
    "size": "60 X 70 CM",
    "technique": "Acrylic on hand-woven cotton fabric",
    "code": "TAH3P034",
    "price": 0,
    "status": "display",
    "series": "illustration",
    "img": "images/art_34.jpg"
  },
  {
    "id": 35,
    "title": "ILLUSTRATION 4",
    "size": "60 X 70 CM",
    "technique": "Acrylic on hand-woven cotton fabric",
    "code": "TAH3P035",
    "price": 0,
    "status": "display",
    "series": "illustration",
    "img": "images/art_35.jpg"
  },
  {
    "id": 36,
    "title": "ILLUSTRATION 5",
    "size": "60 X 70 CM",
    "technique": "Acrylic on hand-woven cotton fabric",
    "code": "TAH3P036",
    "price": 0,
    "status": "display",
    "series": "illustration",
    "img": "images/art_36.jpg"
  },
  {
    "id": 37,
    "title": "ILLUSTRATION 6",
    "size": "60 X 70 CM",
    "technique": "Acrylic on hand-woven cotton fabric",
    "code": "TAH3P037",
    "price": 0,
    "status": "display",
    "series": "illustration",
    "img": "images/art_37.jpg"
  },
  {
    "id": 38,
    "title": "ILLUSTRATION 7",
    "size": "60 X 70 CM",
    "technique": "Acrylic on hand-woven cotton fabric",
    "code": "TAH3P038",
    "price": 0,
    "status": "display",
    "series": "illustration",
    "img": "images/art_38.jpg"
  },
  {
    "id": 39,
    "title": "ILLUSTRATION 8",
    "size": "60 X 70 CM",
    "technique": "Acrylic on hand-woven cotton fabric",
    "code": "TAH3P039",
    "price": 0,
    "status": "display",
    "series": "illustration",
    "img": "images/art_39.jpg"
  },
  {
    "id": 40,
    "title": "RISE AND FALL, OPEN AND CLOSE 1",
    "size": "30 X 20 X 30 CM",
    "technique": "Sculpted using a paper-cement mixture",
    "code": "TAH3P040",
    "price": 8500,
    "status": "sale",
    "series": "sculpture",
    "img": "images/art_40.jpg"
  },
  {
    "id": 41,
    "title": "RISE AND FALL, OPEN AND CLOSE 2",
    "size": "30 X 20 X 30 CM",
    "technique": "Sculpted using a paper-cement mixture",
    "code": "TAH3P041",
    "price": 8500,
    "status": "sale",
    "series": "sculpture",
    "img": "images/art_41.jpg"
  },
  {
    "id": 42,
    "title": "RISE AND FALL, OPEN AND CLOSE 3",
    "size": "30 X 20 X 30 CM",
    "technique": "Sculpted using a paper-cement mixture",
    "code": "TAH3P042",
    "price": 8500,
    "status": "sale",
    "series": "sculpture",
    "img": "images/art_42.jpg"
  }
];
